name: Tests

on:
  pull_request:
  push:
     # trying and staging branches are for Bors config
    branches:
      - trying
      - staging
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rails-version: [5.2, 6.1]
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
      MEILISEARCH_HOST: http://localhost:7700
      MEILISEARCH_API_KEY: masterKey
    name: integration-tests (Rails ${{ matrix.rails-version }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: MeiliSearch (latest) setup with Docker
      run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --master-key=masterKey --no-analytics=true
    - name: Run tests
      run: bundle exec rspec
